LU-18630 misc: fix --without-libarchive build failure
configure --without-libarchive triggers the error:

./../misc/create_inode_libarchive.c: In function ‘__populate_fs_from_tar’:
./../misc/create_inode_libarchive.c:25:34: error: parameter name omitted
 errcode_t __populate_fs_from_tar(ext2_filsys, ext2_ino_t, const char *,
                                  ^~~~~~~~~~~
./../misc/create_inode_libarchive.c:25:47: error: parameter name omitted
 errcode_t __populate_fs_from_tar(ext2_filsys, ext2_ino_t, const char *,
                                               ^~~~~~~~~~
./../misc/create_inode_libarchive.c:25:59: error: parameter name omitted
 errcode_t __populate_fs_from_tar(ext2_filsys, ext2_ino_t, const char *,
                                                           ^~~~~~~~~~~~
./../misc/create_inode_libarchive.c:26:34: error: parameter name omitted
                                  ext2_ino_t, struct hdlinks_s *,
                                  ^~~~~~~~~~
./../misc/create_inode_libarchive.c:26:46: error: parameter name omitted
                                  ext2_ino_t, struct hdlinks_s *,
                                              ^~~~~~~~~~~~~~~~~~
./../misc/create_inode_libarchive.c:27:34: error: parameter name omitted
                                  struct file_info *,
                                  ^~~~~~~~~~~~~~~~~~
./../misc/create_inode_libarchive.c:28:34: error: parameter name omitted
                                  struct fs_ops_callbacks *) {
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: ecfd4dd1217a ("Decouple --without-libarchive and HAVE_ARCHIVE_H")

Change-Id: I1d8313b5a3622eb17515f2f751a7e4dd0df7a2b1
Signed-off-by: Li Dongyang <dongyangli@ddn.com>